import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@jobber/components/header-on-server";
import { HeaderOnClient } from "@jobber/components/header-on-client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ padding: '20px' }}
      >
        <h1 style={{ outline: '1px solid green', display: 'flex',  padding: '10px' }}>LAYOUT HEADER</h1>
        <Nav />
        <HeaderOnClient />
        {children}
      </body>
    </html>
  );
}
