import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@jobber/components/header-on-server";
import { HeaderOnClient } from "@jobber/components/header-on-client";

import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tw = {
  header: 'relative font-black text-cyan-800  px-5 p-2 bg-gradient-to-r from-cyan-100 to-cyan-400 drop-shadow-md drop-shadow-black z-50',
  body: `${geistSans.variable} ${geistMono.variable} antialiased bg-amber-300`,
  content: 'w-3/4 mx-auto p-5'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={tw.body}
      >
        <h1  className={tw.header}>LAYOUT HEADER</h1>
        <Nav />
        <HeaderOnClient />
        <div className={tw.content}>
          {children}
        </div>
      </body>
    </html>
  );
}
